ERROR_USER_EXISTS='ERROR_USER_EXISTS'
ERROR_INVALID_VALUES='ERROR_INVALID_VALUES'

EVENT_VISITED='visited'
EVENT_APPLIED='applied'
EVENT_COMPLETED_QUESTIONNARE='completed_questionnare'
EVENT_ACCEPTED_BG_CHECK='accepted_bg_check'

FUNNELS_START_DATE='start_date'
FUNNELS_END_DATE='end_date'
FUNNELS_DATE_PATTERN='%Y-%m-%d'